### ISSUE TITLE
shared state and multi-threaded use

### ISSUE THREAD

**Issue by carueda** [orangeduck/mpc#155]
Hello!

I'm putting together an MPC-based prototype. In general all good so far. However, as I've added unit tests, I started facing unexpected failures (e.g., `error: Parser Undefined`) for cases that are just fine when run individually. I've reviewed my memory management and the like as usual, including use of valgrind. No issues there. Then I realized that my unit tester dispatches multiple threads by default. When instructed to run all tests in a single thread, all tests complete consistently fine. 

So, I then suspected some shared state in MPC may be the cause, at least in part. I searched for `static[^(]*$` in mpc.c and in fact there's some shared state:

https://github.com/orangeduck/mpc/blob/6e3d2d54aa0ddd22952acaca5806f8b4ef2f51a9/mpc.c#L604

https://github.com/orangeduck/mpc/blob/6e3d2d54aa0ddd22952acaca5806f8b4ef2f51a9/mpc.c#L2492-L2494

In particular, `char_unescape_buffer` seems the most suspicious because it's updated as part of the public `mpc_err_string` function (which is exercised by several of my units tests).

So, this looks like a bug, at least for multi-threaded use. My immediate use case is unit testing, where serialized execution is just fine (they run fast enough), but I'm a bit concerned about actual use of my parser in the future within the context of a multithreaded environment where multiple scripts (in my language) may be concurrently parsed/processed.

I'll take a closer look at mpc.c to see whether fixing this wouldn't take too much effort, but of course, input from the maintainers would be great.

**Comment by orangeduck** [comment]
Yes this doesn't look right good find.

My recommendation would be this: wrap `static char char_unescape_buffer[4];` in a struct and have that struct be the thing returned by `mpc_err_char_unescape`. Callers will then have to access the struct member but this should remove the static variable.

`mpc_escape_input_c` looks less suspect since it is const.

**Comment by carueda** [comment]
Thanks for the comment.  Just submitted a PR with an adjustment for `char_unescape_buffer`.
