### ISSUE TITLE
Create a compiler

### ISSUE THREAD

**Issue by 235689** [orangeduck/mpc#19]
I am reading your book and I would like to know if this parser could be used to build a compiler o this library will be useful only for interpretate a language and not compile it.

**Comment by orangeduck** [comment]
Hi,

This parser can certainly be used to create a compiler. All this library does is read in a program's source code and create an internal representation of it. What you do with that representation (either generate code or interprit it) is up to you. Although I should mention that my book only covers the process of making an interpreter.

Thanks,

Dan
