### ISSUE TITLE
Regex group support

### ISSUE THREAD

**Issue by TheCrafter** [orangeduck/mpc#28]
I have defined a rule like this:

`/(?<comment>[<][*](?(?=[<][*])\g<comment>|.)*?[*][>])/`

but it doesn't seem to work. I use this rule to find comments in a program like this:

```
def hello ():
	
   <* a comment nananana 

    <* a comment nananana 
   BATMAN!!!! *>

   BATMAN!!!! *>

   puts("Hello world!\n")
   
   <* a comment nananana 
   BATMAN!!!! *>

end
```

I was wondering. Does your library support advanced regular expressions like that?

Note: I found the regex I used here: https://regex101.com/r/pP0kG4/3 and I modified it to work on my code. An it seems to work on this website. But in my code it doesn't. 

Am I doing something wrong or you just do not support this?

**Comment by orangeduck** [comment]
Hi,

Sorry this isn't supported in mpc. It doesn't support groups or backreferences or anything like that.

- Dan

**Comment by TheCrafter** [comment]
Oh ok. Thanks for letting me know!
