### ISSUE TITLE
Surprising behaviour from mpc_count parser

### ISSUE THREAD

**Issue by moysesb** [orangeduck/mpc#34]
I think I have stumbled upon a possible violation of [POLA] (https://en.wikipedia.org/wiki/Principle_of_least_astonishment) here.. 

This works as expected:
```c
 mpc_parser_t *p = mpc_count(3, mpcf_strfold, mpc_digit(), free);
 int r = mpc_parse("test", "046", p, &mr);
```
If there's any non-digit input past `count` chars (3 in my example),  the parser also succeeds, as expected:

```c
 mpc_parser_t *p = mpc_count(3, mpcf_strfold, mpc_digit(), free);
 int r = mpc_parse("test", "046aa", p, &mr);
```

But, and this is the behaviour that surprised me, if there are any *digits* beyond `count`, the parser fails, like so:
```c
 mpc_parser_t *p = mpc_count(3, mpcf_strfold, mpc_digit(), free);
 int r = mpc_parse("test", "04632", p, &mr);
```

```bash
$ test:1:6: error: expected 3 of digit at end of input
```
Is this on purpose? I can get around this issue by creating an `mpc_many1` parser and splitting the digits externally, I just want to make sure that I'm not missing something here. 

Oh, and thanks for this awesome library!

**Comment by orangeduck** [comment]
Hi moysesb,

This looks like a bug. Good find! I'll check it out and find out exactly what is wrong.

Thanks,

Dan

**Comment by moysesb** [comment]
Just fyi, the `mpc_re` parser has the same behaviour, e.g.: `mpc_re("\\d{3}")` accepts "046aa" but not "04611".

**Comment by orangeduck** [comment]
Please try 3643fbe6bb1a4fa88db62b24c7a67c3399d64086 where I believe this should now be fixed :+1:

**Comment by moysesb** [comment]
Indeed it works. Thank you very much!

**Comment by orangeduck** [comment]
No problem. Happy Parsing :+1:
