### ISSUE TITLE
[osx] segfault on certain decimal regexes

### ISSUE THREAD

**Issue by dunn** [orangeduck/mpc#39]
Working through http://www.buildyourownlisp.com/chapter6_parsing I found that replacing the decimal-number rule you suggested in https://github.com/orangeduck/mpc/issues/12#issuecomment-53264662 with the following causes a segfault when the REPL is given any input that causes `mpc_parse("<stdin>", input, Lispy, &r)` to evaluate as true:

```diff
diff --git a/repl.c b/repl.c
index 5aa2cf9..b2f26fb 100644
--- a/repl.c
+++ b/repl.c
@@ -12,7 +12,7 @@ int main (int argc, char** argv) {
   mpc_parser_t* Lispy    = mpc_new("lispy");
 
   mpca_lang(MPCA_LANG_DEFAULT, "                 \
-number  : /-?[0-9]+(\\.?[0-9]*)?/ ;              \
+number  : /-?[0-9]*\\.?[0-9]+/ ;                 \
 operator: '+' | '-' | '*' | '/';                 \
 expr    : <number> | '(' <operator> <expr>+ ')' ;\
 lispy   : /^/ <operator> <expr>+ /$/;            \
```
(Full code of `repl.c`: https://gist.github.com/dunn/1176c4ed7b2ba6c5b68e)

Remove the second `\` in front of the decimal and that's a valid regular expression in most contexts, so I don't _think_ this is just a silly typo on my part.

OSX: 10.11.1; same result with Clang and GCC:
```
🌰  clang --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```
```
🌰  gcc-5 --version
gcc-5 (Homebrew gcc 5.2.0) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by je-so** [comment]
The bug is described in Thread "Parsing is extremely slow" and version 932c86 has fixed it for me.

**Comment by dunn** [comment]
Oh, thanks! I forgot to mention I am using 0.8.7, so I'll try building from master.
