### ISSUE TITLE
Parser reuse

### ISSUE THREAD

**Issue by EddieRingle** [orangeduck/mpc#43]
So this issue is a little out of sorts, I guess. I've tried to modify mpc to parse `<base> { <factor> }` instead of `<base> { <digits> }`, as I would like to specify `n`-separated lists of `x` by writing `x{n}` in the grammar.

To begin, I modified `mpcaf_grammar_repeat()` like so:

```C
static mpc_val_t *mpcaf_grammar_repeat(int n, mpc_val_t **xs) {
  (void) n;
  if (xs[1] == NULL) { return xs[0]; }
  if (strcmp(xs[1], "*") == 0) { free(xs[1]); return mpca_many(xs[0]); }
  if (strcmp(xs[1], "+") == 0) { free(xs[1]); return mpca_many1(xs[0]); }
  if (strcmp(xs[1], "?") == 0) { free(xs[1]); return mpca_maybe(xs[0]); }
  if (strcmp(xs[1], "!") == 0) { free(xs[1]); return mpca_not(xs[0]); }
  return mpca_and(2, xs[0], mpca_many(mpca_and(2, xs[1], xs[0])));
}
```

And modified `mpca_lang_st` to define `Factor` as:

```C
mpc_define(Factor, mpc_and(2, mpcaf_grammar_repeat,
    Base,
      mpc_or(6,
        mpc_sym("*"),
        mpc_sym("+"),
        mpc_sym("?"),
        mpc_sym("!"),
        mpc_tok_brackets(Factor, free),
        mpc_pass()),
    mpc_soft_delete
  ));
```

Sample grammar and the result of `mpc_print()`'ing the generated parser:

`list : "text"{","} ;` ->
`(<:> ((<S> ("text" whitespace)) ((<S> ("," whitespace)) (<S> ("text" whitespace)))*))`

So the above looks good, but my problem is that parsing this new grammar seems to be causing a segfault after a few iterations of `mpc_undefine_unretained()` (upon accessing the passed in parser):

<img width="345" alt="screenshot 2016-02-14 16 24 48" src="https://cloud.githubusercontent.com/assets/32543/13036818/a4f338d8-d337-11e5-9f9f-6531b70e2367.png">

Looking at the stack trace, it looks like the calls to `mpc_undefine_and()` match up with the generated parser. The only thing I can think of is that `xs[0]` in the first snippet is being freed and then accessed again in the later and() parser that combines `xs[1]` and `xs[0]`. I'm still not super comfortable with mpc's source so I'm not really sure what to do at this point.

Any ideas?

**Comment by orangeduck** [comment]
Thanks looks interesting - I'll take a look.

**Comment by orangeduck** [comment]
Just looking at the code I also think what you suspected was wrong is wrong.

```
mpca_and(2, xs[0], mpca_many(mpca_and(2, xs[1], xs[0])));
```

In this line `xs[0]` is passed in twice - so it will be freed multiple times. I guess the easiest way to fix this would be to add some kind of `mpc_copy` function so you can pass in a copy of `xs[0]` as one of the arguments (and leave the other as it is).

Probably mpc needs this `mpc_copy` function anyway for these sort of scenarios so probably I should go and add it.

**Comment by orangeduck** [comment]
I've added `mpc_copy` into c2908c37bbf44029fbe9ec9f0f2efdedc42b62a9.

You can try something like:

```
mpca_and(2, mpc_copy(xs[0]), mpca_many(mpca_and(2, xs[1], xs[0])));
```

Hopefully this will work.

**Comment by orangeduck** [comment]
Opps I think this will still have been broken in that commit - but should work in this one: 4da2ae5febfcce003310a0cd2af810272b3a4fa0

**Comment by EddieRingle** [comment]
Thanks @orangeduck! I'll give it a try here soon.
