### ISSUE TITLE
Get children by tag

### ISSUE THREAD

**Issue by petermlm** [orangeduck/mpc#45]
Hello.

Suppose I have an AST with tag "Root" and three children ASTs with the following tags:

 * LeftOperand
 * Operator
 * RightOperand

Suppose I want to get the child AST "Operator" while traversing a tree. Currently I do something like:

```C
mpc_ast_t operator = ast->children[OP_IND]; /* OP_IND == 1 */
```

But if I'm building a big parser and the AST gets very complex, it will be cumbersome to hardcode so many indexes for every node/child combination.

A good way to solve this in the current version is just implement a function that returns the index number given a tag, or returns the pointer to the AST given the tag, like:

```C
int        mpc_ast_get_index(mpc_ast_t *ast, char *tag);
mpc_ast_t *mpc_ast_get_child(mpc_ast_t *ast, char *tag);
```

As far as I explored, MPC doesn't have such a feature. Would this be something practical to have?

(Notice that this the "char *tag" parameter could be replaced by an integer tag identifier like I've discussed in my previous issue.)

**Comment by orangeduck** [comment]
This sounds good - should be simple to implement - I'll look into it.

**Comment by petermlm** [comment]
Thank you!

I can implement it over the next few days if you would like. We could have those exact prototypes. And we could place them after the definition of this function:

```C
mpc_ast_t *mpc_ast_state(mpc_ast_t *a, mpc_state_t s);
```

**Comment by orangeduck** [comment]
Sounds good :+1:
