### ISSUE TITLE
First example doesn't work - print_ast is passed a value_t

### ISSUE THREAD

**Issue by ASkeptic** [orangeduck/mpc#46]
Looks like r.output isn't an mpc_ast_t*, it is a mpc_val_t*

Not only that, I'm not sure how to convert a val_t to an  ast_t

I am missing something obvious or does the very first example not compile?

  mpc_result_t r;

  if(mpc_parse("input", input, Maths, &r)) {
    mpc_ast_print(r.output);
    mpc_ast_delete(r.output);
  } else {

**Comment by orangeduck** [comment]
Hi,

`mpc_val_t*` is actually just a `void*`. So in this case it is safe to cast to/interprit as `mpc_ast_t*` because you know this is the output type of your parser `Maths`.

- Dan

**Comment by ASkeptic** [comment]
That was a lightning fast response, thanks.  

I'm guessing the error is because I'm compiling in C++ which won't automatically cast from void*

There are actually multiple functions that end up being confusing:

mpc_val_t *mpcf_fold_ast(int n, mpc_val_t **as);
mpc_val_t *mpcf_str_ast(mpc_val_t *c);
mpc_val_t *mpcf_state_ast(int n, mpc_val_t **xs);

Because they take what looks like a different type there ends up being a hidden barrier to entry if using C++ (I'm using visual studio).  I would guess this has stopped quite a few people unnecessarily.   Maybe val_t can be taken out and made into ast_t ? (I throw that out so I'm not just pointing out problems but I've only been looking at the source for the last 10 minutes)

**Comment by ASkeptic** [comment]
Also I changed two lines to avoid warnings (default level 3) with msvc:

2026:   range[strlen(range) + 0] = (char)j;
2148:   *y = (float)strtod(x, NULL);

**Comment by orangeduck** [comment]
Yeah that will probably be why. Perhaps I will add a little note for C++ users (I've not actually tested this library in C++). Unfortunately using `void*` is the only way to get this behaviour in native C as not all parsers return a `mpc_ast_t*`.

**Comment by ASkeptic** [comment]
One more thing that it took for me to get it to work - I had to use extern "C" around the header include so that the names weren't mangled (which breaks linking).

extern "C" {
  #include "mpc.h"
}

The functions that take multiple struct wrappers around void* would work if the arguments were void*, C++ won't cast from void* to another type, but it will allow a void* to take any pointer type.

I have this working:
void mpc_ast_delete(void* mpc_ast_or_val_type)
{
  mpc_ast_t* a = (mpc_ast_t*)(mpc_ast_or_val_type);
...

**Comment by orangeduck** [comment]
Yeah I think this is kind of standard with C++. `mpc` isn't really a C++ library which is why you're having these issues. Did you have to make these changes to get it to compile - or just to use it?

**Comment by ASkeptic** [comment]
I'm not exactly sure of the question but I might be able to answer it anyway - I had to make that change to be able to compile the first example in visual studio while using the .h and .c files directly.

**Comment by orangeduck** [comment]
Okay thats fine. I think for now there is not a problem (the issues you had are normal procedure when using a C library with C++), but I will look into making it a bit easier later on.
