### ISSUE TITLE
Unable to use a dot in a regex.

### ISSUE THREAD

**Issue by LambdaProgrammer** [orangeduck/mpc#47]
Hello, 
I am trying to implement a double type in my Build Your Own Lisp language. I am using this regex to parse them: `/-?[0-9]+\\.[0-9]+/`. When I try to use a double in my REPL, I get a parser error. I am very confused, because I have the dot escaped properly.

The exact error is `<stdin>:1:10: error: expected one of '0123456789', '-', one or more of one of '0123456789', one or more of one of 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUV
WXYZ0123456789_+-^%*/\=<>!&', '"', '#', '(', '[' or end of input at '.'
`

Why am I getting this error? Is this a bug?

**Comment by orangeduck** [comment]
Hey,

Its unlikely this is a bug and more likely there is something wrong with your grammar somewhere. To me your actual regex looks okay but you might have issues elsewhere in your grammar. You can take a look at these other issues (#29, #12, #10) for people who have had similar issues.

- Dan

**Comment by LambdaProgrammer** [comment]
@orangeduck  My problem seems to be different. Here is my full grammar.
```
  Int          = mpc_new("int");
  Double       = mpc_new("double");
  Symbol       = mpc_new("symbol");
  String       = mpc_new("string");
  Generator    = mpc_new("generator");
  Comment      = mpc_new("comment");
  Sexpr        = mpc_new("sexpr");
  List         = mpc_new("list");
  Expr         = mpc_new("expr");
  Lispy        = mpc_new("lispy");

  mpca_lang(MPCA_LANG_DEFAULT,"                                         \
      int            : /-?[0-9]+/ ;                                     \
      double         : /-?[0-9]+\\.[0-9]+/;                             \
      symbol         : /[a-zA-Z0-9_+\\-^%*\\/\\\\=<>!&]+/ ;             \
      generator      : '{' <expr> '|' <list> '}';                       \
      string         : /\"(\\\\.|[^\"])*\"/ ;                           \
      comment        : /#[^\r\n]*/ ;                                    \
      sexpr          : '(' <expr>* ')' ;                                \
      list           : '[' <expr>* ']' ;                                \
      expr           : <int>  | <symbol> | <string>                     \
                     | <comment> | <sexpr> | <list> ;                   \
      lispy          : /^/ <expr>* /$/ ;                                ",
    Int, Double, Symbol, Generator, String, Comment, Sexpr, List, Expr, Lispy);
```

Sorry for bothering you.

**Comment by orangeduck** [comment]
Looks like you haven't included your `double` rule as an option for an `expr`. Also make sure you list it as an option before `int` see: https://github.com/orangeduck/mpc#backtracking-isnt-working

**Comment by LambdaProgrammer** [comment]
@orangeduck Thank you so much.

**Comment by saifali96** [comment]
@LambdaProgrammer Can you please post your latest grammar in which you implemented Double numbers?
@orangeduck I'll really request you to make a repository in which you do all the bonus tasks in your book and explain regex in a bit more detail, just in case people get stuck.
:)
