### ISSUE TITLE
Tree traversal iterator

### ISSUE THREAD

**Issue by petermlm** [orangeduck/mpc#49]
Like we've started discussing in #48, the idea is to have a simple way to traverse a tree in either pre order or post order.

To start we have the following save point:

```
typedef struct mpc_ast_trav_t {
    mpc_ast_t             *curr_node;
    struct mpc_ast_trav_t *parent;
    int                    curr_child;
    mpc_ast_trav_order_t   order;
} mpc_ast_trav_t;
```

The order type is the following enum:

```
typedef enum {
    mpc_ast_trav_order_pre,
    mpc_ast_trav_order_post
} mpc_ast_trav_order_t;
```

Using the start function:

```
mpc_ast_trav_t *mpc_ast_traverse_start(mpc_ast_t *ast,
                                       mpc_ast_trav_order_t order);
```

We get a saving point which just keeps information about the current location in the tree. To iterate through it we ca use the "next" function:

```
mpc_ast_t *mpc_ast_traverse_next(mpc_ast_trav_t *trav);
```

The idea is that we can traverse the whole tree using only the next function. It will be practical in some applications. For example, to convert the whole tree to another specification (Like we've discussed in a previous issue where we wanted to convert from `mpc_ast_t` to another tree specification)

I've already started implementing these functions, but haven't finished yet.

Note that for now I've only thought about two order, pre and post. Pre order will make "next" function yield nodes "x", "a", "b", in the following tree:

```
  X
 / \
A   B
```

While post order would make "next" yield "a", "b", "x". Note also that because the trees are not necessarily binary, we don't get infix, prefix, or postfix.

**Comment by orangeduck** [comment]
Sounds good :+1:

**Comment by saifali96** [comment]
This isn't probably the best place to ask, but can you help me in working out a regex in mpc to allow numbers in floating representation?
currently using this for non-floating integers:
`"number	:	/-?[0-9]+/;"`

**Comment by orangeduck** [comment]
Hi @saifali96 - not really the correct place, but you can check out these issues #10 #12 #47
