### ISSUE TITLE
2 warnings when compiling on Windows

### ISSUE THREAD

**Issue by petermlm** [orangeduck/mpc#51]
When I tried compiling MPC for windows using Visual Studio 2015 Update 2 I got a few warnings regarding the usage of functions like strcpy. I'm not particularly worried about those warnings so I just use a few flags to remove them. But two other warnings still show up.

One of the warning is in [this function](https://github.com/orangeduck/mpc/blob/master/mpc.c#L2218). The function strtod uses doubles but the return value expects a float. To solve we just use the function `strtof`.

The other is in [this line](https://github.com/orangeduck/mpc/blob/master/mpc.c#L2098). There is a size_t being cast to char. This is not incorrect in terms of usage, but the compiler still complains. To remove this warning we can use an explicit cast like so:

```
range[strlen(range) + 0] = (char) j;
```

That will work unless there is an error in the function and j should be a char.

**Comment by orangeduck** [comment]
Thanks. I will look into this this weekend and verify on my side. I've also had some thoughts with regards to the integer tags and such so will try to merge in your other requests and make some updates.

**Comment by petermlm** [comment]
Nice. Looking forward to it!

**Comment by orangeduck** [comment]
This should be fixed in 14001ad33269a3e36222dcd761df1d2889717789. Thanks.
