### ISSUE TITLE
Infinite loop - why?

### ISSUE THREAD

**Issue by cmaughan** [orangeduck/mpc#55]
I've been trying to write some code to ignore anything inside a scope (including nested brackets)
The grammar looks like this:

```
ignore_body "Body"  :  '{' <ignore_body>* '}' | /[^{}]*/ ;
func "Function"  :  <func_decl> '{' <ignore_body>* '}' ;
```
Any ideas why this would loop?  I find debugging this hard, because the mpc core code is difficult to unpick....

**Comment by cmaughan** [comment]
(fixed the text!)

**Comment by orangeduck** [comment]
Hard to say - have an example input you are testing it on?

**Comment by cmaughan** [comment]
Even this will fail in my case:
void func() { }

**Comment by orangeduck** [comment]
Hmm. Looking again I think this is because `/[^{}]*/` matches the empty string and `<ignore_body>*` therefore matches zero or more empty strings. Zero or more empty strings can always be found and the system runs forever.

**Comment by cmaughan** [comment]
Wow - so simple!  I've been staring at that for quite some time!!  Thanks :)
