### ISSUE TITLE
Basic grammar for Maths expressions 

### ISSUE THREAD

**Issue by janus** [orangeduck/mpc#59]
Hello,

The below fails when I have basic Math expressions like: 9 + 8

`
  mpca_lang(MPCA_LANG_DEFAULT,
    "                                                     \
      number   : /-?[0-9]+/ ;                             \
      operator : '*' | '/' ;                  \
      oper     : '+' | '-'  ;                  \
      factor   : <number> | '(' <expr> ')' ; 		\
      term     : <factor> | <factor> <operator> <term>  ; 		\
      expr     : <term> | <term> <oper> <expr>  ;  		 \
      lispy    : /^/ <expr> /$/ ;             \
    ",
    Number, Operator, Oper,Factor, Term, Expr, Lispy);

`
The below passed. The only difference is the position of "term" and "factor"  where I have union operator in the grammar. Could someone explain why this?
`
  mpca_lang(MPCA_LANG_DEFAULT,
    "                                                     \
      number   : /-?[0-9]+/ ;                             \
      operator : '*' | '/' ;                  \
      oper     : '+' | '-'  ;                  \
      factor   : <number> | '(' <expr> ')' ; 		\
      term     : <factor> <operator> <term> | <factor>  ; 		\
      expr     :<term> <oper> <expr>  | <term>   ;  		 \
      lispy    : /^/ <expr> /$/ ;             \
    ",
    Number, Operator, Oper,Factor, Term, Expr, Lispy);

`

**Comment by orangeduck** [comment]
I think your formatting is messed up so I can't see what you intended but the order of the union operator matters because it defines in which order the various options are tried. See the FAQ: https://github.com/orangeduck/mpc#limitations--faq

**Comment by janus** [comment]
@orangeduck  Merci ...
