### ISSUE TITLE
"extern C" for C++ linking

### ISSUE THREAD

**Issue by Trebgarta** [orangeduck/mpc#61]
Just adding an extern C in a ifdef macro in the header would be nice. I mean, I cant think of any downsides personally.

I tried using mpc in CPP, and while I should have been aware I wasnt, so I was clueless for half an hour wondering why the references were undefined.

**Comment by orangeduck** [comment]
Although personally I prefer to do it on the include side of things E.G

```c++
extern "C" {
#include "mpc.h"
}
```

I can't see any harm in adding it to the mpc header so I've added it in d6375f813dae054f9b26b6ce1bebf5b532fe2a89.

**Comment by Trebgarta** [comment]
Well Ill be damned, not sure how I forgot that too.

Anyway, thanks for the quick response!
