### ISSUE TITLE
Valgrind Errors

### ISSUE THREAD

**Issue by howerj** [orangeduck/mpc#63]
Hi! 

Just wanted to say this is I really like the library, but I had two issues with it. There appears to be
a few memory related problems, I solved this in my project which used by mpc with a wrapper
around realloc, and replacing all instances of realloc with it:

> static void *reallocate(void *p, size_t n)
> {
>  /**@bug something is not allocating enough memory, the +1 fixes the Valgrind issues*/
>  errno = 0;
>  void *r = realloc(p, n+1); 
>  if(!r)
>    fatal("reallocate failed: %s", errno ? strerror(errno) : "unknown reason");
>  return r;
> }
> As a temporary fix.

This problem is reproducible with mpcs "test" program. I've attached the output of valgrind. Presumably one of the reallocs somewhere is missing a +1 or something.

The second, minor, issue, I get the same build error as in https://github.com/orangeduck/mpc/issues/60, as strtof was introduced in c99, specify the ansi flag means the strtof definition is never defined, which is allowed behavior. The fix would be to specify -std=c99 in the makefile as c99 functions are used. 

Output of _uname -a_:

> Linux dhcppc2 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

This was on commit 37c12b1d43605c2b897b4bacd6d45c450920aea4.

Thanks!

[mpc.txt](https://github.com/orangeduck/mpc/files/517861/mpc.txt)

**Comment by orangeduck** [comment]
Hi @howerj,

Thanks for the excellent report. I will check this out as soon as I can. Sometimes mpc throws valgrind errors which aren't actually issues when compiling with `-O3` due to SIMD type optimisation of string operations. But let me double check this to make sure it isn't that issue.

For #60 I'll probably change the function to use `atof` instead which is still C89.

- Dan

**Comment by howerj** [comment]
Cheers, The errors do disappear at the lower optimization level.
