### ISSUE TITLE
Warnings (cyclomatic_complexity > 15 or length > 1000 or parameter_count > 100)

### ISSUE THREAD

**Issue by datomnurdin** [orangeduck/mpc#71]
I'm using Lizard plugin (https://github.com/terryyin/lizard) to analyze Cyclomatic Complexity on MPC. I found these after analysis?

 NLOC    CCN   token  PARAM  length  location  

     170     62   1790      4     221 mpc_parse_run@1009-1229@mpc.c
      34     19    241      2      46 mpc_undefine_unretained@1324-1369@mpc.c
      60     21    631      1      74 mpc_copy@1406-1479@mpc.c
      21     17    222      1      21 mpc_re_escape_char@2033-2053@mpc.c
      95     30    863      2     113 mpc_print_unretained@2479-2591@mpc.c
      28     17    300      2      37 mpcf_fold_ast@2994-3030@mpc.c
      28     16    379      2      38 mpc_nodecount_unretained@3615-3652@mpc.c
     137     58   2304      2     166 mpc_optimise_unretained@3660-3825@mpc.c

How I can reduce future defect on future? Please advice. TQ

**Comment by orangeduck** [comment]
What exactly is the issue? What is "future defect"?
