### ISSUE TITLE
Problem with grammar comprehension, some elements are ignored during parsing

### ISSUE THREAD

**Issue by jimy-byerley** [orangeduck/mpc#73]
Hi orangeduck, this microparser is a great idea, In my current project it's saving me from many hours of coding.
I use it to recognize C-like expressions, but I currently have an error I dont understand.
here is a simplifed version with the same error:

```
#include <stdio.h>
#include <mpc.h>

int main(int argc, const char * argv[])
{
	if (argc <= 1)
	{
		fprintf(stderr, "was waiting for a file as argument 1\n");
		return -1;
	}
	
	mpc_parser_t * expr		= mpc_new("expression");
	mpc_parser_t * sum		= mpc_new("sum");
	
	mpc_parser_t * all	= mpc_new("all");
	
	mpc_parser_t * access	= mpc_new("access");
	mpc_parser_t * addr		= mpc_new("address");
	mpc_parser_t * name		= mpc_new("name");
	
	
	mpca_lang(MPCA_LANG_PREDICTIVE,
			  " expression :		(<access> '=' <sum>) | <sum>; "
			  " sum :			<access> (('+' | '-') <access>)*; "
			  " access :	('&' | '*')? <address>; "
			  " address :	(<name> ('.' <name>)*) | ('(' <expression> ')' ('.' <name>)*); "
			  " name :	/[a-zA-Z0-9]+/; "
			  " all :	/^/ <expression> /$/; ",
			  expr, sum, access, addr, name, all, 0);
	mpc_result_t result;
	
	printf("parser ok\n");
	if (!mpc_parse_contents(argv[1], all, &result))
	{
		mpc_err_print(result.error);
		mpc_err_delete(result.error);
		return -1;
	}
	
	// read the retreived elements, use a recursive function
	mpc_ast_t * tree = result.output;
	printf("parsing finished\n");
	mpc_ast_print(tree);
	
	return 0;
}
```
I use the following expression:
`temp.a = (2+4) - 5`

when I execute it it get the following message:

`mpc-test:1:12: error: expected one of 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', '.', '=', '&', '*', one or more of one of 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' or '(' at '+'
`
It seems that mpc does'nt see the character '2' before '+'  as if it was parsing an "access" before a "sum"

**Comment by orangeduck** [comment]
Hi,

I think the problem is that it looks like your grammar is not predictive. Try removing the `MPCA_LANG_PREDICTIVE` flag and see if that helps.

- Dan

**Comment by jimy-byerley** [comment]
Thanks, I just tested it  with `MPCA_LANG_DEFAULT` and it works. What is the difference between predictive grammar and not predictive one ?
Can you possibly add an error message in case of fail of the parser because of lack of predictiveness ?

**Comment by orangeduck** [comment]
Predictive grammars are `LL(1)` - that means it is always possible tell the result of the parse by looking on character ahead. There are some more details in the docs.

Unfortunately I don't think it is something that is easy to check for but I will look it up. If it is possible to check for then probably I can change mpc to just detect predictiveness automatically and apply it where possible.
