### ISSUE TITLE
how to build and use`mpc` as static library?

### ISSUE THREAD

**Issue by ghost** [orangeduck/mpc#75]
I had configured `c` build process via `clang`, `-Weverything`, `-Werror`, etc.

So, when I build tutorial-based project that use `mpc` included header fails with a lot of `mpc` compilation errors.

I don't know how to configure build to ignore warnings from specific file (

So, how to build `mpc` as a statc library?

**Comment by orangeduck** [comment]
Just remove `-Werror`.
